label: Content
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
      fields:
        title:
          label: Title
        type:
          separator: ', '
        status:
          label: Status
          settings:
            format_custom_true: Published
        operations:
          label: Operations
      filters:
        title:
          expose:
            label: Title
        status:
          expose:
            label: Status
          group_info:
            group_items:
              1:
                title: Published
        langcode:
          expose:
            label: Language
      title: Content
    display_title: Master
  page_1:
    display_options:
      menu:
        title: Content
      tab_options:
        title: Content
    display_title: Page
