display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        user_bulk_form:
          label: 'Bulk update'
        status:
          label: Status
          settings:
            format_custom_true: Active
        operations:
          label: Operations
        mail:
          separator: ', '
      filters:
        status:
          group_info:
            label: Status
            group_items:
              1:
                title: Active
  page_1:
    display_title: Page
