display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        redirect_bulk_form:
          action_title: 'With selection'
        redirect_source__path:
          label: From
          separator: ', '
        created:
          label: Created
      filters:
        redirect_source__path:
          expose:
            label: From
        redirect_redirect__uri:
          expose:
            label: To
        language:
          expose:
            label: 'Original language'
  page_1:
    display_title: Page
