display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        filename:
          label: Name
          separator: ', '
        status:
          label: Status
      filters:
        status:
          expose:
            label: Status
  page_2:
    display_options:
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        count:
          format_plural_string: !!binary MQNAY291bnQ=
      arguments:
        fid:
          exception:
            title: All
