_core:
  default_config_hash: N67AkcKPlikWJbwxABv6MSMpGuXe36qWZfH88pEzeqc
add_page_meta: true
output_terms: true
output_fields: true
lib_helper: false
entity_meta:
  created: '0'
  langcode: '0'
  name: '0'
  status: '0'
  uid: '0'
  uuid: '0'
  vid: '0'
enable_ia: false
ia_depth: 3
ia_category_primary: primaryCategory
ia_category_sub: subCategory
vocabs:
  action: '0'
  case_type: '0'
  code: '0'
  jcc_form_category: '0'
  jcc_form_prefix: '0'
  party: '0'
expose_user_details: ''
expose_user_details_roles:
  authenticated: '0'
  editor: '0'
  jcc_web_services: '0'
  administrator: '0'
current_user_meta:
  name: '0'
  mail: '0'
  roles: '0'
  created: '0'
  access: '0'
group: false
expose_user_details_fields: false
entity_title: entityTitle
entity_type: entityType
entity_bundle: entityBundle
entity_identifier: entityId
group_label: groupLabel
drupal_language: drupalLanguage
drupal_country: drupalCountry
site_name: siteName
key_replacements:
  - ''
