ignore_admin_paths: true
ignore_ajax_links: true
ignore_hashes: true
ignore_file_ext: true
url_patterns_to_ignore: ''
selector: ''
allowed_domains: ''
prefetch_only_paths: ''
no_load_when_authenticated: true
no_load_when_session: false
no_load_content_types: {  }
load_polyfill: false
enable_debug_mode: false
