apikey: sendgrid
test_defaults:
  to: hosting@chapterthree.com
  subject: 'Test Email from SendGrid Module'
  body:
    value: "<p>Test <strong>Message</strong> for SendGrid.</p>\r\n"
    format: basic_html
  from_name: ''
  to_name: ''
  reply_to: ''
_core:
  default_config_hash: g4qz7cPnloXFwtnLYfIKI2VS0gf_UFOz_I2uQiiulC8
